
#pragma once

#define MESSAGE_BUFFER_SIZE 250

#include <Arduino.h>
#include <Stepper.h>
#include <Servo.h>
#include "../component/MD25.h"
#include "../component/SharpIR.h"
#include "../robot.h"
#include "../activities.h"
#include "../debug.h"
#include "../timeout.h"

#define ACTIVITY_ROTATE_CAROUSEL 1
#define ACTIVITY_ROTATE_CAROUSEL_HALF 2
#define ACTIVITY_LOWER_ARM 3
#define ACTIVITY_RAISE_ARM 4
#define ACTIVITY_BLINK_LED 5
#define ACTIVITY_LOWER_ARM_FROM_TOP_TO_SIDE 10
#define ACTIVITY_RAISE_ARM_FROM_SIDE_TO_TOP_RED 11
#define ACTIVITY_RAISE_ARM_FROM_SIDE_TO_TOP_GREEN 12
#define ACTIVITY_RAISE_ARM_FROM_SIDE_TO_TOP_BLUE 13
#define ACTIVITY_LOWER_ARM_INTO_CAROUSEL 14
#define ACTIVITY_RAISE_ARM_FROM_CAROUSEL 15
#define ACTIVITY_PUT_IN_WEIGHING_SCALES 20
#define ACTIVITY_RETRACT_FROM_WEIGHING_SCALES 21
#define ACTIVITY_PICK_INTO_CAROUSEL 22
#define ACTIVITY_PICK_FROM_CAROUSEL 23
#define ACTIVITY_PUT_ON_PARTICLE_ACCELERATOR 24
#define ACTIVITY_PULL_BACK_PARTICLE_ACCELERATOR 25
#define ACTIVITY_ALLOW_ROTATE 26
#define ACTIVITY_UN_ALLOW_ROTATE 27
#define ACTIVITY_ARM_POSITION_PA 30
#define ACTIVITY_ARM_POSITION_PA_RETRACT 31
#define ACTIVITY_ARM_POSITION_GOLDIUM 35
#define ACTIVITY_ARM_POSITION_GOLDIUM_RETRACT 36
#define ACTIVITY_DROP_GOLDIUM 37
#define ACTIVITY_DROP_GOLDIUM_RETRACT 38
#define ACTIVITY_PULL_CORD 100
#define ACTIVITY_PULL_CORD_INSERT 101
#define ACTIVITY_RAISE_ARM_FROM_SIDE_TO_REST 102
#define ACTIVITY_SLOW_ARM 200
#define ACTIVITY_FAST_ARM 201
#define ACTIVITY_ROTATE_CAROUSEL_5 250
#define ACTIVITY_ALIGN_FORWARD 251

#define PULL_CORD_PIN 12

#define PRIMARY_SERVO_PIN 4
#define SECONDARY_SERVO_PIN 3
#define GRABBER_SERVO_PIN 2

#define FRONT_ALIGNMENT_SERVO_1_PIN undefined
#define FRONT_ALIGNMENT_SERVO_2_PIN undefined

#define ARM_STEPPER_SPEED_FAST 105
#define ARM_STEPPER_SPEED_SLOW 90
#define CAROUSEL_STEPPER_SPEED 70
#define STEPPER_ROTATIONS 200

#define ARM_STEPPER_1 22
#define ARM_STEPPER_2 24
#define ARM_STEPPER_3 26
#define ARM_STEPPER_4 28

#define CAROUSEL_STEPPER_1 8
#define CAROUSEL_STEPPER_2 9
#define CAROUSEL_STEPPER_3 10
#define CAROUSEL_STEPPER_4 11

#define ARM_GRABBER_CLOSED 12
#define ARM_GRABBER_OPEN 55

uint16_t readComponentValue(uint16_t component_ID);

Activity* lookupActivity(uint16_t activity_ID);
